version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: ""
  MYSQL_DATABASE: ingress
  REACT_APP_INGRESS_BACKEND_URL: 4000

services:
  mysql:
    image: mysql:8.0.24
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./backend/db/migration.sql:/docker-entrypoint-initdb.d/sample.sql
  backend:
    build: ./backend
    depends_on:
      - mysql
    expose:
      - 4000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    links:
      - mysql
    command: npm start
  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - backend
    command: npm start