version: "3.2"
services:
  nodejs:
    build: 
      context: ./backend
    image: node:14
    networks:
      - backend
    environment:
      - MYSQL_HOST=ingress-mysql-app
      - MYSQL_USER=ingressuser
      - MYSQL_PASS=ingresspass
      - MYSQL_DB=ingress
      - KAFKA_CLIENT_ID="INGRESS"
      - KAFKA_BROKERS=kafka1:9092,kafka2:9092
    volumes:
      - .:/code
    ports:
      - "3000:4000"
    container_name: ingress-nodejs-app
    depends_on: 
      - mysql
  mysql:
    image: mysql:5.7
    # command: default-authentication-plugin=mysql_native_password
    # volumes: 
    #   - ./backend/db/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ingressuser
      - MYSQL_PASSWORD=ingresspass 
      - MYSQL_DATABASE=ingress
    # expose:
    #   - "3306"
    ports:
      - "3306:3306"
    restart: always
    container_name: ingress-mysql-db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "3001:80"
    environment:
      - PMA_HOST=ingress-mysql-db
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: ingress-phpmyadmin-app
networks:
  backend:
